# Generated by Django 5.2 on 2025-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('commentaire', models.TextField()),
                ('note', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='avis_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='avis_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='avis_photos/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='avis_photos/')),
                ('valide', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('annee_adhesion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'phone')},
            },
        ),
    ]
