# Generated by Django 5.1.5 on 2025-02-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madcap_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='avis_photos/'),
        ),
        migrations.AddField(
            model_name='avis',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='avis_photos/'),
        ),
        migrations.AddField(
            model_name='avis',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='avis_photos/'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('name', 'phone')},
        ),
    ]
