# Generated by Django 5.1.5 on 2025-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madcap_app', '0002_avis_photo1_avis_photo2_avis_photo3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='avis_photos/'),
        ),
    ]
