# Generated by Django 5.1.5 on 2025-02-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madcap_app', '0003_avis_photo4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'ordering': ['-date']},
        ),
    ]
